INSERT INTO USER (USER_ID, EMAIL, USERNAME, PASSWORD, NICKNAME, ROLE) VALUES (1, 'ss@ss.com', 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'ROLE_ADMIN');

INSERT INTO ROLES (ROLE_NAME) values ('ROLE_USER');
INSERT INTO ROLES (ROLE_NAME) values ('ROLE_ADMIN');

INSERT INTO USER_ROLES (USER_ID, ROLE_NAME) values (1, 'ROLE_USER');
INSERT INTO USER_ROLES (USER_ID, ROLE_NAME) values (1, 'ROLE_ADMIN');